apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocket-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pocket-pv/"
